# Generated by Django 4.0.3 on 2022-04-10 10:33

from django.db import migrations, models


# models.py에서 지정한 대로 만들어준다. ($ python manage.py makemigrations)
# $ python manage.py migrate 를 입력하고 나서
# $ python manage.py dbshell을 입력하면 데이터베이스 shell이 열린다.
# >  PRAGMA table_info(my_to_do_app_todo) 테이블 정보 확인


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo', 
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
            ],
        ),
    ]

